version: "3"

services:
  ecommerce:
    build:
      context: .
    ports:
    - "8000:8000"
    volumes:
    - ./ecommerce:/ecommerce
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"