# Generated by Django 3.1.2 on 2021-03-18 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_productvariation_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariation',
            name='description',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='name',
        ),
    ]
