# Generated by Django 3.1.2 on 2021-03-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_auto_20210318_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='variation_image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
