# Generated by Django 3.1.2 on 2021-03-19 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_auto_20210319_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='brand_variations', to='product.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_variations', to='product.category'),
        ),
    ]
