# Generated by Django 3.1.2 on 2021-03-19 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_remove_product_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariation',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='product.category'),
        ),
    ]
