# Generated by Django 3.1.5 on 2021-03-21 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='is_slider',
            field=models.BooleanField(default=False),
        ),
    ]
