# Generated by Django 3.1.2 on 2021-03-22 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_productvariation_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='category',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='product.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='product.color'),
        ),
    ]
