# Generated by Django 3.1.2 on 2021-03-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_auto_20210324_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='parent_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(default=250000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='parent_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
