# Generated by Django 3.1.2 on 2021-03-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_auto_20210324_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productattributes',
            old_name='is_import',
            new_name='is_main',
        ),
        migrations.RenameField(
            model_name='productattributes',
            old_name='product_code',
            new_name='key',
        ),
        migrations.RenameField(
            model_name='productattributes',
            old_name='size',
            new_name='label',
        ),
        migrations.RemoveField(
            model_name='productattributes',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='productattributes',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productattributes',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productattributes',
            name='description',
        ),
        migrations.RemoveField(
            model_name='productattributes',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='productattributes',
            name='name',
        ),
        migrations.RemoveField(
            model_name='productattributes',
            name='price',
        ),
        migrations.RemoveField(
            model_name='productattributes',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='productattributes',
            name='variation_image',
        ),
        migrations.AddField(
            model_name='productattributes',
            name='value',
            field=models.CharField(default=123, max_length=255),
            preserve_default=False,
        ),
    ]
