# Generated by Django 3.1.2 on 2021-03-24 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_auto_20210324_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattributes',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='product.product'),
        ),
    ]
