# Generated by Django 3.1.5 on 2021-03-24 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0035_auto_20210324_1504'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Color',
        ),
    ]
