# Generated by Django 3.1.2 on 2021-03-25 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0040_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
    ]
