# Generated by Django 3.1.5 on 2021-03-26 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0042_auto_20210325_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
