# Generated by Django 3.1.2 on 2021-04-04 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0047_category_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='created_at',
            new_name='updated_at',
        ),
    ]
