# Generated by Django 3.1.5 on 2021-02-17 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20210215_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='product',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='cart_product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cart.cartproduct'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
