# Generated by Django 3.1.2 on 2021-03-06 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_order_cart_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
