# Generated by Django 3.1.5 on 2021-03-07 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart_product',
        ),
    ]
