# Generated by Django 3.1.2 on 2021-03-13 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_cartproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartProduct',
        ),
    ]
