# Generated by Django 3.1.2 on 2021-03-14 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0022_delete_sendpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbeta',
            name='finish_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
