# Generated by Django 3.1.5 on 2021-03-15 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0024_auto_20210315_1347'),
        ('cart', '0024_auto_20210315_1402'),
    ]

    operations = [
    ]
