# Generated by Django 3.1.2 on 2021-03-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0028_orderbeta_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbeta',
            name='status',
            field=models.CharField(choices=[('K', 'waiting'), ('J', 'send'), ('Y', 'finished')], max_length=255, null=True),
        ),
    ]
