# Generated by Django 3.1.2 on 2021-03-20 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0029_orderbeta_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbeta',
            name='status',
            field=models.CharField(choices=[('W', 'waiting'), ('S', 'send'), ('F', 'finished')], max_length=255, null=True),
        ),
    ]
