# Generated by Django 3.1.2 on 2021-03-20 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0031_auto_20210320_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderbeta',
            name='is_finished',
        ),
    ]
