# Generated by Django 3.1.2 on 2021-03-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0032_remove_orderbeta_is_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbeta',
            name='status',
            field=models.CharField(choices=[('T', 'Tushgan'), ('W', 'Kutilmoqda'), ('S', "Jo'natilgan"), ('F', 'Tugallangan')], default='T', max_length=255),
        ),
    ]
