# Generated by Django 3.1.2 on 2021-03-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0033_auto_20210320_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbeta',
            name='status',
            field=models.CharField(choices=[('T', 'Tushgan'), ('W', 'Kutilmoqda'), ('C', 'Bekor qilingan'), ('F', 'Tugallangan')], default='T', max_length=255),
        ),
    ]
