# Generated by Django 3.1.5 on 2021-03-21 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0034_auto_20210320_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderbeta',
            name='status',
            field=models.CharField(choices=[('Tushgan', 'Tushgan'), ('Kutilmoqda', 'Kutilmoqda'), ('Bekor qilingan', 'Bekor qilingan'), ('Tugallangan', 'Tugallangan')], default='Tushgan', max_length=255),
        ),
    ]
