# Generated by Django 3.1.2 on 2021-05-08 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0042_auto_20210407_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbeta',
            name='status',
            field=models.CharField(choices=[('Kutilmoqda', 'Kutilmoqda'), ("Jo'natilgan", "Jo'natilgan"), ('Bekor qilingan', 'Bekor qilingan'), ('Tugallangan', 'Tugallangan')], default='Kutilmoqda', max_length=255),
        ),
    ]
