# Generated by Django 3.1.2 on 2021-05-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0044_auto_20210511_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbeta',
            name='status',
            field=models.CharField(choices=[('Tushgan', 'Tushgan'), ("Jo'natilgan", "Jo'natilgan"), ('Bekor qilingan', 'Bekor qilingan'), ('Tugallangan', 'Tugallangan')], default='Kutilmoqda', max_length=255),
        ),
    ]
