# Generated by Django 3.1.5 on 2021-02-11 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210209_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_import',
            field=models.BooleanField(default=False),
        ),
    ]
