# Generated by Django 3.1.2 on 2021-03-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20210315_1438'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Size',
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='', editable=False),
        ),
    ]
