# Generated by Django 3.1.2 on 2021-03-17 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20210316_1219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariation',
            old_name='product',
            new_name='parent',
        ),
    ]
