# Generated by Django 3.1.2 on 2021-03-18 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20210317_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='product.category'),
            preserve_default=False,
        ),
    ]
