# Generated by Django 3.1.2 on 2021-03-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20210318_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
