# Generated by Django 3.1.2 on 2021-03-19 04:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_productvariation_variation_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvariation',
            name='is_import',
            field=models.BooleanField(default=False),
        ),
    ]
