# Generated by Django 3.1.2 on 2021-03-19 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_auto_20210319_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariation',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='product.brand'),
        ),
    ]
