# Generated by Django 3.1.2 on 2021-03-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_auto_20210322_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='product_code',
            field=models.CharField(default=25545, max_length=255),
            preserve_default=False,
        ),
    ]
