# Generated by Django 3.1.2 on 2021-03-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_productvariation_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariation',
            name='product_code',
            field=models.CharField(max_length=7),
        ),
    ]
