# Generated by Django 3.1.2 on 2021-03-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_auto_20210324_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_import', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('variation_image', models.ImageField(upload_to='')),
                ('size', models.CharField(max_length=255)),
                ('price', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('product_code', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='parent',
        ),
    ]
