# Generated by Django 3.1.2 on 2021-03-25 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0038_auto_20210325_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.CharField(default=12345, max_length=7),
            preserve_default=False,
        ),
    ]
