# Generated by Django 3.1.2 on 2021-03-26 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0044_product_image'),
        ('product', '0043_auto_20210326_0935'),
    ]

    operations = [
    ]
