# Generated by Django 3.1.5 on 2021-04-05 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0048_auto_20210404_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='is_slider',
        ),
    ]
