# Generated by Django 3.1.5 on 2021-02-26 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cart_cartproduct_history_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart_product',
        ),
    ]
