# Generated by Django 3.1.5 on 2021-02-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_remove_order_cart_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart_product',
            field=models.ManyToManyField(to='cart.CartProduct'),
        ),
    ]
