# Generated by Django 3.1.2 on 2021-03-12 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_auto_20210309_1013'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartProduct',
        ),
    ]
