# Generated by Django 3.1.2 on 2021-03-13 11:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20210310_1115'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0015_phoneverify_verify_kod'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PhoneVerify',
            new_name='SendPassword',
        ),
    ]
