# Generated by Django 3.1.2 on 2021-03-13 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0016_auto_20210313_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendpassword',
            name='product',
        ),
    ]
