# Generated by Django 3.1.2 on 2021-03-14 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20210310_1115'),
        ('cart', '0017_remove_sendpassword_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderBeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('phone_number', models.CharField(max_length=15)),
                ('count', models.PositiveIntegerField()),
                ('overall_price', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
