# Generated by Django 3.1.2 on 2021-03-14 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0019_auto_20210314_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproductbeta',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderproductbeta',
            name='product',
        ),
        migrations.DeleteModel(
            name='OrderBeta',
        ),
        migrations.DeleteModel(
            name='OrderProductBeta',
        ),
    ]
