# Generated by Django 3.1.5 on 2021-03-14 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0021_orderbeta_orderproductbeta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SendPassword',
        ),
    ]
