# Generated by Django 3.1.5 on 2021-03-15 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0023_auto_20210314_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproductbeta',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderproducts', to='cart.orderbeta'),
        ),
    ]
