# Generated by Django 3.1.5 on 2021-03-16 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20210316_1219'),
        ('cart', '0025_merge_20210315_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproductbeta',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productvariation'),
        ),
    ]
