# Generated by Django 3.1.2 on 2021-03-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0026_auto_20210316_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='status',
        ),
        migrations.AddField(
            model_name='orderbeta',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
