# Generated by Django 3.1.2 on 2021-03-19 12:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0027_auto_20210319_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbeta',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
