# Generated by Django 3.1.2 on 2021-03-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0035_auto_20210321_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproductbeta',
            name='product_code',
            field=models.CharField(default=25545, max_length=255),
            preserve_default=False,
        ),
    ]
