# Generated by Django 3.1.2 on 2021-03-31 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0039_auto_20210326_1023'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
