# Generated by Django 3.1.2 on 2021-04-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0040_delete_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbeta',
            name='phone_number',
            field=models.CharField(max_length=17),
        ),
    ]
