# Generated by Django 3.1.5 on 2021-04-07 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0041_auto_20210405_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbeta',
            name='phone_number',
            field=models.CharField(max_length=255),
        ),
    ]
