# Generated by Django 3.1.2 on 2021-05-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0046_auto_20210512_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbeta',
            name='status',
            field=models.CharField(choices=[('Tushgan', 'Tushgan'), ('Kutilmoqda', 'Kutilmoqda'), ('Bekor qilingan', 'Bekor qilingan'), ('Tugallangan', 'Tugallangan')], default='Tushgan', max_length=255),
        ),
    ]
